version: '2'
services:
    erpjhipsterapplication-app:
        image: erpjhipsterapplication
        environment:
            - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mariadb://erpjhipsterapplication-mariadb:3306/erpjhipsterapplication
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_JEST_URI=http://erpjhipsterapplication-elasticsearch:9200
            - SPRING_CLOUD_STREAM_KAFKA_BINDER_BROKERS=kafka
            - SPRING_CLOUD_STREAM_KAFKA_BINDER_ZK_NODES=zookeeper
    erpjhipsterapplication-mariadb:
        extends:
            file: mariadb.yml
            service: erpjhipsterapplication-mariadb
    erpjhipsterapplication-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: erpjhipsterapplication-elasticsearch
    kafka:
        extends:
            file: kafka.yml
            service: kafka
        environment:
            - KAFKA_ADVERTISED_HOST_NAME=kafka
    zookeeper:
        extends:
            file: kafka.yml
            service: zookeeper
